/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        assertEquals(Telex.telexToVietnamese("muawj"), "mựa")
    }
}
